name: Go
on: [push, pull_request]
jobs:
  build:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1.0.2
        id: go
        with:
          version: "1.x"

      - uses: actions/checkout@v1.0.0

      - name: install deps
        run: |
          go mod download
          (
            cd /tmp
            env GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          )

      - name: run-linter
        run: |
          $(go env GOPATH)/bin/golangci-lint run
        env:
          GOPROXY: off
          GOFLAGS: -mod=readonly

      - name: go-build
        run: go build
        env:
          GOPROXY: off
          GOFLAGS: -mod=readonly
