name: Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "42 2 * * 2"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        id: go
        with:
          go-version: 1.x

      - uses: actions/checkout@v2.3.4

      - run: go build
        env:
          GOFLAGS: -mod=readonly

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: golangci/golangci-lint-action@v2.3.0
