name: Go
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "42 2 * * 2"
jobs:
  build:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@master
        id: go
        with:
          go-version: 1.14

      - uses: actions/checkout@v2.3.1

      - name: install deps
        run: |
          go mod download
          (
            cd /tmp
            env GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          )

      - name: run-linter
        run: golangci-lint run
        env:
          GOPROXY: off
          GOFLAGS: -mod=readonly

      - name: go-build
        run: go build
        env:
          GOPROXY: off
          GOFLAGS: -mod=readonly
