name: Go
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go_version:
          - 1.12.x
          - 1.13.x

    name: Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        id: go
        with:
          version: ${{ matrix.go_version }}

      - uses: actions/checkout@master

      - name: go-mod-download
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: go-build
        run: go build -mod readonly
