name: docker-tests
on:
  pull_request:
    branches:
      - master
    paths:
      - Dockerfile
jobs:
  test-root-dockerfile:
    name: test root dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0

      - name: test Dockerfile
        uses: docker://docker
        with:
          entrypoint: docker
          args: build .
